<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ESBTPMatiereSeeder extends Seeder
{
    /**
     * Seeder pour créer les matières des différentes filières de l'ESBTP.
     *
     * @return void
     */
    public function run()
    {
        // Récupérer l'ID de la filière MGP
        $filiereMGP = DB::table('esbtp_filieres')->where('code', 'MGP')->first();
        
        if (!$filiereMGP) {
            $this->command->error('La filière MGP n\'existe pas. Veuillez d\'abord exécuter le seeder ESBTPFiliereSeeder.');
            return;
        }
        
        // Récupérer les IDs des niveaux d'études
        $niveauBTS1 = DB::table('esbtp_niveau_etudes')->where('code', 'BTS1')->first();
        $niveauBTS2 = DB::table('esbtp_niveau_etudes')->where('code', 'BTS2')->first();
        
        if (!$niveauBTS1 || !$niveauBTS2) {
            $this->command->error('Les niveaux d\'études BTS1 ou BTS2 n\'existent pas. Veuillez d\'abord exécuter le seeder ESBTPNiveauEtudeSeeder.');
            return;
        }
        
        // Formation Générale pour MGP
        $formationGenerale = [
            [
                'code' => 'TEOC',
                'name' => 'TEOC',
                'nom' => 'Technique d\'expression écrite et orale/communication/documentation',
                'description' => 'Cours de communication et documentation technique',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'generale',
                'heures_cm' => 20,
                'heures_td' => 20,
                'heures_tp' => 0,
                'heures_stage' => 0,
                'heures_perso' => 20,
                'coefficient' => 2,
                'couleur' => '#3498db',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'TEOC2',
                'name' => 'TEOC2',
                'nom' => 'Technique d\'expression écrite et orale/communication/documentation',
                'description' => 'Cours de communication et documentation technique - Niveau avancé',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS2->id,
                'type_formation' => 'generale',
                'heures_cm' => 10,
                'heures_td' => 10,
                'heures_tp' => 0,
                'heures_stage' => 0,
                'heures_perso' => 10,
                'coefficient' => 2,
                'couleur' => '#3498db',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ANG1',
                'name' => 'ANG1',
                'nom' => 'Anglais technique',
                'description' => 'Apprentissage de l\'anglais technique et professionnel',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'generale',
                'heures_cm' => 15,
                'heures_td' => 25,
                'heures_tp' => 0,
                'heures_stage' => 0,
                'heures_perso' => 20,
                'coefficient' => 2,
                'couleur' => '#2ecc71',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ANG2',
                'name' => 'ANG2',
                'nom' => 'Anglais technique',
                'description' => 'Anglais technique avancé appliqué au domaine professionnel',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS2->id,
                'type_formation' => 'generale',
                'heures_cm' => 10,
                'heures_td' => 20,
                'heures_tp' => 0,
                'heures_stage' => 0,
                'heures_perso' => 10,
                'coefficient' => 2,
                'couleur' => '#2ecc71',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ECO1',
                'name' => 'ECO1',
                'nom' => 'Économie et Gestion',
                'description' => 'Principes d\'économie et de gestion appliqués au secteur',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'generale',
                'heures_cm' => 20,
                'heures_td' => 10,
                'heures_tp' => 0,
                'heures_stage' => 0,
                'heures_perso' => 10,
                'coefficient' => 2,
                'couleur' => '#e74c3c',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'DROIT1',
                'name' => 'DROIT1',
                'nom' => 'Droit',
                'description' => 'Principes juridiques appliqués au secteur',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'generale',
                'heures_cm' => 20,
                'heures_td' => 10,
                'heures_tp' => 0,
                'heures_stage' => 0,
                'heures_perso' => 10,
                'coefficient' => 2,
                'couleur' => '#9b59b6',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MATH1',
                'name' => 'MATH1',
                'nom' => 'Mathématiques',
                'description' => 'Mathématiques appliquées au génie civil',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 30,
                'heures_td' => 30,
                'heures_tp' => 0,
                'heures_stage' => 0,
                'heures_perso' => 20,
                'coefficient' => 3,
                'couleur' => '#f1c40f',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MATH2',
                'name' => 'MATH2',
                'nom' => 'Mathématiques appliquées',
                'description' => 'Mathématiques avancées pour les applications en génie civil',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS2->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 20,
                'heures_td' => 20,
                'heures_tp' => 0,
                'heures_stage' => 0,
                'heures_perso' => 20,
                'coefficient' => 3,
                'couleur' => '#f1c40f',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PHYS1',
                'name' => 'PHYS1',
                'nom' => 'Sciences Physiques',
                'description' => 'Physique appliquée au bâtiment et aux travaux publics',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 30,
                'heures_td' => 20,
                'heures_tp' => 10,
                'heures_stage' => 0,
                'heures_perso' => 20,
                'coefficient' => 3,
                'couleur' => '#e67e22',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'CHIM1',
                'name' => 'CHIM1',
                'nom' => 'Chimie',
                'description' => 'Principes de chimie appliqués au secteur',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 20,
                'heures_td' => 10,
                'heures_tp' => 0,
                'heures_stage' => 0,
                'heures_perso' => 10,
                'coefficient' => 2,
                'couleur' => '#95a5a6',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'INFO1',
                'name' => 'INFO1',
                'nom' => 'Informatique appliquée',
                'description' => 'Initiation à l\'informatique et aux logiciels spécialisés',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 20,
                'heures_td' => 10,
                'heures_tp' => 0,
                'heures_stage' => 0,
                'heures_perso' => 10,
                'coefficient' => 2,
                'couleur' => '#95a5a6',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'CAO1',
                'name' => 'CAO1',
                'nom' => 'CAO/DAO',
                'description' => 'Conception et dessin assistés par ordinateur',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 20,
                'heures_td' => 10,
                'heures_tp' => 0,
                'heures_stage' => 0,
                'heures_perso' => 10,
                'coefficient' => 2,
                'couleur' => '#95a5a6',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ENTR2',
                'name' => 'ENTR2',
                'nom' => 'Entreprenariat',
                'description' => 'Formation à l\'entreprenariat et à la gestion de projet',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS2->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 20,
                'heures_td' => 10,
                'heures_tp' => 0,
                'heures_stage' => 0,
                'heures_perso' => 10,
                'coefficient' => 2,
                'couleur' => '#95a5a6',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        
        // Utilisation de la méthode insertOrIgnore pour éviter les doublons
        DB::table('esbtp_matieres')->insertOrIgnore($formationGenerale);
        
        $this->command->info('Les matières ESBTP ont été créées avec succès.');
    }
} 