<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ESBTPMatiereSeeder extends Seeder
{
    /**
     * Seeder pour créer les matières des différentes filières de l'ESBTP.
     *
     * @return void
     */
    public function run()
    {
        // Récupérer l'ID de la filière MGP
        $filiereMGP = DB::table('esbtp_filieres')->where('code', 'MGP')->first();
        
        if (!$filiereMGP) {
            $this->command->error('La filière MGP n\'existe pas. Veuillez d\'abord exécuter le seeder ESBTPFiliereSeeder.');
            return;
        }
        
        // Récupérer les IDs des niveaux d'études
        $niveauBTS1 = DB::table('esbtp_niveau_etudes')->where('code', 'BTS1')->first();
        $niveauBTS2 = DB::table('esbtp_niveau_etudes')->where('code', 'BTS2')->first();
        
        if (!$niveauBTS1 || !$niveauBTS2) {
            $this->command->error('Les niveaux d\'études BTS1 ou BTS2 n\'existent pas. Veuillez d\'abord exécuter le seeder ESBTPNiveauEtudeSeeder.');
            return;
        }
        
        // Récupérer les IDs des types de formation
        $formationGeneraleType = DB::table('esbtp_formations')->where('code', 'FG')->first();
        $formationTechnoProType = DB::table('esbtp_formations')->where('code', 'FTP')->first();
        
        if (!$formationGeneraleType || !$formationTechnoProType) {
            $this->command->error('Les types de formation n\'existent pas. Veuillez d\'abord exécuter le seeder ESBTPFormationSeeder.');
            return;
        }
        
        // Formation Générale pour MGP
        $formationGenerale = [
            [
                'code' => 'TEOC1',
                'name' => 'TEOC1',
                'nom' => 'Technique d\'expression écrite et orale/communication/documentation',
                'description' => 'Cours de communication et documentation technique - 1ère année',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'generale',
                'heures_cm' => 20,
                'heures_td' => 20,
                'heures_tp' => 0,
                'coefficient_default' => 2,
                'total_heures_default' => 40,
                'couleur' => '#3498db',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'TEOC2',
                'name' => 'TEOC2',
                'nom' => 'Technique d\'expression écrite et orale/communication/documentation',
                'description' => 'Cours de communication et documentation technique - 2ème année',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS2->id,
                'type_formation' => 'generale',
                'heures_cm' => 10,
                'heures_td' => 10,
                'heures_tp' => 0,
                'coefficient_default' => 2,
                'total_heures_default' => 20,
                'couleur' => '#3498db',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ANG1',
                'name' => 'ANG1',
                'nom' => 'Anglais technique',
                'description' => 'Apprentissage de l\'anglais technique et professionnel - 1ère année',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'generale',
                'heures_cm' => 20,
                'heures_td' => 20,
                'heures_tp' => 0,
                'coefficient_default' => 2,
                'total_heures_default' => 40,
                'couleur' => '#2ecc71',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ANG2',
                'name' => 'ANG2',
                'nom' => 'Anglais technique',
                'description' => 'Anglais technique avancé appliqué au domaine professionnel - 2ème année',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS2->id,
                'type_formation' => 'generale',
                'heures_cm' => 15,
                'heures_td' => 15,
                'heures_tp' => 0,
                'coefficient_default' => 2,
                'total_heures_default' => 30,
                'couleur' => '#2ecc71',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ECO1',
                'name' => 'ECO1',
                'nom' => 'Économie et Gestion',
                'description' => 'Principes d\'économie et de gestion appliqués au secteur',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'generale',
                'heures_cm' => 20,
                'heures_td' => 10,
                'heures_tp' => 0,
                'coefficient_default' => 2,
                'total_heures_default' => 30,
                'couleur' => '#e74c3c',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'DROIT1',
                'name' => 'DROIT1',
                'nom' => 'Droit',
                'description' => 'Principes juridiques appliqués au secteur',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'generale',
                'heures_cm' => 20,
                'heures_td' => 10,
                'heures_tp' => 0,
                'coefficient_default' => 2,
                'total_heures_default' => 30,
                'couleur' => '#9b59b6',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Formation Technologique et Professionnelle pour MGP
        $formationTechPro = [
            [
                'code' => 'MATH1',
                'name' => 'MATH1',
                'nom' => 'Mathématiques',
                'description' => 'Mathématiques appliquées au domaine MGP',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 20,
                'heures_td' => 20,
                'heures_tp' => 0,
                'coefficient_default' => 3,
                'total_heures_default' => 40,
                'couleur' => '#f1c40f',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PHYS1',
                'name' => 'PHYS1',
                'nom' => 'Physique (statique et résistance des matériaux)',
                'description' => 'Physique appliquée au domaine MGP',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 20,
                'heures_td' => 20,
                'heures_tp' => 10,
                'coefficient_default' => 3,
                'total_heures_default' => 50,
                'couleur' => '#e67e22',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'CHIM1',
                'name' => 'CHIM1',
                'nom' => 'Chimie',
                'description' => 'Principes de chimie appliqués au secteur MGP',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 20,
                'heures_td' => 10,
                'heures_tp' => 10,
                'coefficient_default' => 2,
                'total_heures_default' => 40,
                'couleur' => '#95a5a6',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'INFO1',
                'name' => 'INFO1',
                'nom' => 'Informatique appliquée',
                'description' => 'Initiation à l\'informatique et aux logiciels spécialisés',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 15,
                'heures_td' => 15,
                'heures_tp' => 10,
                'coefficient_default' => 2,
                'total_heures_default' => 40,
                'couleur' => '#34495e',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'CAO1',
                'name' => 'CAO1',
                'nom' => 'CAO/DAO',
                'description' => 'Conception et dessin assistés par ordinateur',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 10,
                'heures_td' => 10,
                'heures_tp' => 20,
                'coefficient_default' => 2,
                'total_heures_default' => 40,
                'couleur' => '#1abc9c',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'GEOL1',
                'name' => 'GEOL1',
                'nom' => 'Géologie générale',
                'description' => 'Introduction aux principes de géologie',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 20,
                'heures_td' => 10,
                'heures_tp' => 10,
                'coefficient_default' => 3,
                'total_heures_default' => 40,
                'couleur' => '#d35400',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'TOPO1',
                'name' => 'TOPO1',
                'nom' => 'Calculs topométriques',
                'description' => 'Méthodes de calcul topométrique',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 20,
                'heures_td' => 20,
                'heures_tp' => 10,
                'coefficient_default' => 3,
                'total_heures_default' => 50,
                'couleur' => '#16a085',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'DPLAN1',
                'name' => 'DPLAN1',
                'nom' => 'Dessins plans topographiques',
                'description' => 'Techniques de création et interprétation de plans topographiques',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 15,
                'heures_td' => 15,
                'heures_tp' => 20,
                'coefficient_default' => 3,
                'total_heures_default' => 50,
                'couleur' => '#27ae60',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'TPT1',
                'name' => 'TPT1',
                'nom' => 'Travaux pratiques de topométrie',
                'description' => 'Utilisation des instruments et techniques de mesure topographique sur le terrain',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 10,
                'heures_td' => 10,
                'heures_tp' => 30,
                'coefficient_default' => 3,
                'total_heures_default' => 50,
                'couleur' => '#2980b9',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'TOPA1',
                'name' => 'TOPA1',
                'nom' => 'Topométrie appliquée',
                'description' => 'Application des concepts topométriques aux situations réelles',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 15,
                'heures_td' => 15,
                'heures_tp' => 20,
                'coefficient_default' => 3,
                'total_heures_default' => 50,
                'couleur' => '#8e44ad',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'LOT1',
                'name' => 'LOT1',
                'nom' => 'Lotissement',
                'description' => 'Principes et techniques de lotissement urbain et rural',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 20,
                'heures_td' => 20,
                'heures_tp' => 10,
                'coefficient_default' => 3,
                'total_heures_default' => 50,
                'couleur' => '#c0392b',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PHOTO1',
                'name' => 'PHOTO1',
                'nom' => 'Travaux de photogramétrie/cartographie',
                'description' => 'Techniques de photogrammétrie et cartographie appliquées',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 15,
                'heures_td' => 15,
                'heures_tp' => 20,
                'coefficient_default' => 3,
                'total_heures_default' => 50,
                'couleur' => '#d35400',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'GEO1',
                'name' => 'GEO1',
                'nom' => 'Géodésie (canevas géodésiques)',
                'description' => 'Principes fondamentaux de géodésie et création de canevas géodésiques',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 20,
                'heures_td' => 15,
                'heures_tp' => 15,
                'coefficient_default' => 3,
                'total_heures_default' => 50,
                'couleur' => '#f39c12',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'AFON1',
                'name' => 'AFON1',
                'nom' => 'Travaux d\'aménagement foncier et cadastral',
                'description' => 'Droit foncier et cadastre: principes et applications',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 20,
                'heures_td' => 20,
                'heures_tp' => 10,
                'coefficient_default' => 3,
                'total_heures_default' => 50,
                'couleur' => '#2c3e50',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ORG1',
                'name' => 'ORG1',
                'nom' => 'Organisation et gestion des chantiers et des cabinets',
                'description' => 'Méthodes de gestion et d\'organisation professionnelle',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 20,
                'heures_td' => 10,
                'heures_tp' => 0,
                'coefficient_default' => 2,
                'total_heures_default' => 30,
                'couleur' => '#7f8c8d',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PHAER1',
                'name' => 'PHAER1',
                'nom' => 'Photographie aérienne',
                'description' => 'Techniques de photographie aérienne et applications (Cours, TD, TP)',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 15,
                'heures_td' => 15,
                'heures_tp' => 20,
                'coefficient_default' => 3,
                'total_heures_default' => 50,
                'couleur' => '#3498db',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SIG1',
                'name' => 'SIG1',
                'nom' => 'Système d\'informations géographiques',
                'description' => 'Principes et utilisation des SIG dans le contexte professionnel',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 15,
                'heures_td' => 15,
                'heures_tp' => 20,
                'coefficient_default' => 3,
                'total_heures_default' => 50,
                'couleur' => '#2ecc71',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'TELE1',
                'name' => 'TELE1',
                'nom' => 'Télédetection',
                'description' => 'Principes et applications de la télédétection',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 15,
                'heures_td' => 15,
                'heures_tp' => 20,
                'coefficient_default' => 3,
                'total_heures_default' => 50,
                'couleur' => '#9b59b6',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'AUST1',
                'name' => 'AUST1',
                'nom' => 'Travaux d\'auscultation d\'ouvrages et de génie civil',
                'description' => 'Techniques d\'auscultation et de surveillance des ouvrages',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS1->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 15,
                'heures_td' => 15,
                'heures_tp' => 20,
                'coefficient_default' => 3,
                'total_heures_default' => 50,
                'couleur' => '#e74c3c',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ENTR2',
                'name' => 'ENTR2',
                'nom' => 'Entreprenariat',
                'description' => 'Formation à l\'entreprenariat et à la gestion de projet',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS2->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 20,
                'heures_td' => 10,
                'heures_tp' => 0,
                'coefficient_default' => 2,
                'total_heures_default' => 30,
                'couleur' => '#7f8c8d',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PFE2',
                'name' => 'PFE2',
                'nom' => 'Projet de fin d\'études',
                'description' => 'Projet de fin d\'études en MGP',
                'filiere_id' => $filiereMGP->id,
                'niveau_etude_id' => $niveauBTS2->id,
                'type_formation' => 'technologique_professionnelle',
                'heures_cm' => 0,
                'heures_td' => 0,
                'heures_tp' => 60,
                'coefficient_default' => 5,
                'total_heures_default' => 60,
                'couleur' => '#c0392b',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        
        // Utilisation de la méthode insertOrIgnore pour éviter les doublons
        DB::table('esbtp_matieres')->insertOrIgnore($formationGenerale);
        DB::table('esbtp_matieres')->insertOrIgnore($formationTechPro);
        
        $this->command->info('Les matières ESBTP ont été créées avec succès.');
    }
} 